# 'DriverName' values should be either of 'Android', 'iOS', 'BrowserStack-Android', 'BrowserStack-iOS', 'LambdaTest-Android', 'LambdaTest-iOS'
DriverName               = Android

AndroidCapabilities      ={ 'deviceName':'', 'platformVersion':'13.0', 'appPackage':'com.saucelabs.mydemoapp.android', 'appActivity':'com.saucelabs.mydemoapp.android.view.activities.SplashActivity', 'noReset':'false'}
iOSCapabilities          ={ 'deviceName':'', 'platformVersion':'18.2', 'udid':'29EA159B-7E7F-4323-A1FD-6E2AB17E4CBD', 'bundleId':'com.saucelabs.mydemo.app.ios', 'noReset':'false'}
BrowserstackCapabilities = {'userName':'', 'accessKey':'', 'app':'', 'deviceName':'', 'platformVersion':'13', 'buildName':'Android Build'}
LambdaTestCapabilities   = {'userName':'', 'accessKey':'', 'app':'', 'deviceName':'', 'platformVersion':'17', 'build':'iOS Build'}

# Wait time in seconds to wait for an element
WaitTime=10